services:
  roundcube:
    image: ghcr.io/hezzit-agency/roundcube:latest
    restart: unless-stopped
    ports:
      # Adjust the exposed port based on the selected RUN_MODE:
      #- "8080:80"   # Use this for RUN_MODE=full (internal Nginx)
      - "9000:9000"   # Use this for RUN_MODE=fpm-only (external Nginx). Adjust to match your external Nginx config.
    environment:
      # --- Mode Selection ---
      RUN_MODE: "fpm-only"         # Set to "full" or "fpm-only"
      # --- Upload and Memory Limits ---
      MAX_UPLOAD_SIZE: "100M"      # Max upload size, e.g., 100M or 1G
      PHP_MEMORY_LIMIT: "256M"     # PHP memory limit, e.g., 256M or 512M
      # --- Timezone (Optional) ---
      #TZ: "Europe/London"        # Examples: "America/Sao_Paulo", "Europe/Paris", "America/New_York"
      # --- Roundcube DES_KEY Checker (Optional) ---
      # Use to activate or deactivate the DES_KEY checker, preventing or not initialization (DEFAULT "false")
      #ROUNDCUBE_SKIP_DES_KEY_CHECK: "true" #OR "false"
      ################################
      # NOTE: Roundcube-specific settings (DB, SMTP, IMAP, DES_KEY, etc.)
      # should be configured directly in the mounted config.inc.php file below.
      ################################
    volumes:
      # --- Main Roundcube Configuration File ---
      - ./roundcube_data/config.inc.php:/var/www/html/config/config.inc.php:ro
      # --- Custom Plugins and Skins ---
      - ./roundcube_data/plugins:/custom_plugins:ro
      - ./roundcube_data/skins:/custom_skins:ro
      # --- Logs and Temp Files (Optional Persistence) ---
      - ./roundcube_data/logs:/var/www/html/logs
      - ./roundcube_data/temp:/var/www/html/temp
      # --- Additional PHP Configuration (Optional) ---
      # Use this file for additional PHP directives.
      # Avoid setting upload_max_filesize, post_max_size, and memory_limit here if using ENV variables above.
      - ./roundcube_data/php.ini:/usr/local/etc/php/conf.d/zz-custom.ini:ro
    healthcheck:
      # Healthcheck ensures proper startup based on the RUN_MODE
      test: ["CMD-SHELL", "MODE=$${RUN_MODE:-full}; if [ \"$$MODE\" = \"fpm-only\" ]; then supervisorctl status php-fpm | grep -q RUNNING; else supervisorctl status php-fpm | grep -q RUNNING && supervisorctl status nginx | grep -q RUNNING; fi"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

